### ISSUE TITLE
SimulateTimeout doesn't work anymore with .NET 7

### ISSUE THREAD

**Issue by dnperfors** [dnperfors/TestableHttpClient#154]
**Describe the bug**
SimulateTimeout() reports "Operation was canceled." This is because of this following check:
https://github.com/dotnet/runtime/blob/release/7.0/src/libraries/System.Net.Http/src/System/Net/Http/HttpClient.cs#L614

**To Reproduce**
Run the tests with .NET 7

**Background (please complete the following information):**
 - Version of dotnet core: 7

**Comment by dnperfors** [comment]
Other tests fail as well:
```
[xUnit.net 00:00:03.11]     TestableHttpClient.Tests.HttpResponseMessageBuilderTests.WithStringContent_WithEncoding_CreatesHttpResponseMessageWithContentTypeHeader [FAIL]
[xUnit.net 00:00:03.11]     TestableHttpClient.Tests.HttpResponseMessageBuilderTests.WithStringContent_CreatesHttpResponseMessageWithStringContent [FAIL]
[xUnit.net 00:00:03.11]     TestableHttpClient.Tests.HttpResponseMessageBuilderTests.WithStringContent_WithNullMediaType_CreateHttpResponseMessageWithDefaultMediaType [FAIL]
  Failed TestableHttpClient.Tests.HttpResponseMessageBuilderTests.WithStringContent_WithEncoding_CreatesHttpResponseMessageWithContentTypeHeader [< 1 ms]
  Error Message:
   System.ArgumentException : The value cannot be null or empty. (Parameter 'mediaType')
  Stack Trace:
     at System.Net.Http.Headers.MediaTypeHeaderValue.CheckMediaTypeFormat(String mediaType, String parameterName)
   at System.Net.Http.StringContent..ctor(String content, Encoding encoding, String mediaType)
   at TestableHttpClient.HttpResponseMessageBuilder.WithStringContent(String content, Encoding encoding, String mediaType) in C:\dev\TestableHttpClient\src\TestableHttpClient\HttpResponseMessageBuilder.cs:line 117
   at TestableHttpClient.HttpResponseMessageBuilder.WithStringContent(String content, Encoding encoding) in C:\dev\TestableHttpClient\src\TestableHttpClient\HttpResponseMessageBuilder.cs:line 100
   at TestableHttpClient.Tests.HttpResponseMessageBuilderTests.WithStringContent_WithEncoding_CreatesHttpResponseMessageWithContentTypeHeader() in C:\dev\TestableHttpClient\test\TestableHttpClient.Tests\HttpResponseMessageBuilderTests.cs:line 132
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
  Failed TestableHttpClient.Tests.HttpResponseMessageBuilderTests.WithStringContent_CreatesHttpResponseMessageWithStringContent [1 ms]
  Error Message:
   System.ArgumentException : The value cannot be null or empty. (Parameter 'mediaType')
  Stack Trace:
     at System.Net.Http.Headers.MediaTypeHeaderValue.CheckMediaTypeFormat(String mediaType, String parameterName)
   at System.Net.Http.StringContent..ctor(String content, Encoding encoding, String mediaType)
   at TestableHttpClient.HttpResponseMessageBuilder.WithStringContent(String content, Encoding encoding, String mediaType) in C:\dev\TestableHttpClient\src\TestableHttpClient\HttpResponseMessageBuilder.cs:line 117
   at TestableHttpClient.HttpResponseMessageBuilder.WithStringContent(String content) in C:\dev\TestableHttpClient\src\TestableHttpClient\HttpResponseMessageBuilder.cs:line 89
   at TestableHttpClient.Tests.HttpResponseMessageBuilderTests.WithStringContent_CreatesHttpResponseMessageWithStringContent() in C:\dev\TestableHttpClient\test\TestableHttpClient.Tests\HttpResponseMessageBuilderTests.cs:line 109
--- End of stack trace from previous location ---
  Failed TestableHttpClient.Tests.HttpResponseMessageBuilderTests.WithStringContent_WithNullMediaType_CreateHttpResponseMessageWithDefaultMediaType [< 1 ms]
  Error Message:
   System.ArgumentException : The value cannot be null or empty. (Parameter 'mediaType')
  Stack Trace:
     at System.Net.Http.Headers.MediaTypeHeaderValue.CheckMediaTypeFormat(String mediaType, String parameterName)
   at System.Net.Http.StringContent..ctor(String content, Encoding encoding, String mediaType)
   at TestableHttpClient.HttpResponseMessageBuilder.WithStringContent(String content, Encoding encoding, String mediaType) in C:\dev\TestableHttpClient\src\TestableHttpClient\HttpResponseMessageBuilder.cs:line 117
   at TestableHttpClient.Tests.HttpResponseMessageBuilderTests.WithStringContent_WithNullMediaType_CreateHttpResponseMessageWithDefaultMediaType() in C:\dev\TestableHttpClient\test\TestableHttpClient.Tests\HttpResponseMessageBuilderTests.cs:line 143
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
[xUnit.net 00:00:03.11]     TestableHttpClient.Tests.HttpResponseMessageBuilderTests.WithStringContent_WithNullEncoding_CreateHttpResponseMessageWithDefaultEncoding [FAIL]
  Failed TestableHttpClient.Tests.HttpResponseMessageBuilderTests.WithStringContent_WithNullEncoding_CreateHttpResponseMessageWithDefaultEncoding [< 1 ms]
  Error Message:
   System.ArgumentException : The value cannot be null or empty. (Parameter 'mediaType')
  Stack Trace:
     at System.Net.Http.Headers.MediaTypeHeaderValue.CheckMediaTypeFormat(String mediaType, String parameterName)
   at System.Net.Http.StringContent..ctor(String content, Encoding encoding, String mediaType)
   at TestableHttpClient.HttpResponseMessageBuilder.WithStringContent(String content, Encoding encoding, String mediaType) in C:\dev\TestableHttpClient\src\TestableHttpClient\HttpResponseMessageBuilder.cs:line 117
   at TestableHttpClient.HttpResponseMessageBuilder.WithStringContent(String content, Encoding encoding) in C:\dev\TestableHttpClient\src\TestableHttpClient\HttpResponseMessageBuilder.cs:line 100
   at TestableHttpClient.Tests.HttpResponseMessageBuilderTests.WithStringContent_WithNullEncoding_CreateHttpResponseMessageWithDefaultEncoding() in C:\dev\TestableHttpClient\test\TestableHttpClient.Tests\HttpResponseMessageBuilderTests.cs:line 121
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)

Failed!  - Failed:     4, Passed:   370, Skipped:     0, Total:   374, Duration: 198 ms - TestableHttpClient.Tests.dll (net7.0)
```
This is because StringContent now no longer allows a null value for the third parameter (mediatype). When null the default value "text/plain" should be passed.
